### ISSUE TITLE
可以指定不同文件转换，对应的设置vw视口宽度吗？

### ISSUE THREAD

**Issue by learnguos** [evrone/postcss-px-to-viewport#127]

**Comment by Jonny-china** [comment]
我根据这个仓库添加了rules参数，支持路径自定义规则，但是必须是PostCss8以上版本。[这里](https://github.com/Jonny-china/postcss-px-to-viewport#rules-prop)

**Comment by tcstory** [comment]
https://github.com/tcstory/postcss-px-to-viewport

我自己二次开发的插件, 支持 postcss 8.x 以上,  支持你想要的功能

```css
/* px-to-viewport-define landscapeWidth=600, viewportWidth=480 */
.rule {
  font-size: 15px;
  height: 50px;
}
```
